s3: fix typo
fluent/fluentd-docs-gitbook pull request #278
Opened 2021-03-04 15:52 UTC by jazzdan

2021-03-05 00:09 UTC, ashie approved these changes

2021-03-05 00:10 UTC, ashie requested changes
Could you follow DCO? https://github.com/fluent/fluentd-docs-gitbook/pull/278/checks?check_run_id=2032517589

2021-03-08 19:26 UTC, jazzdan commented
@ashie I followed the instructions, sorry for the delay!

2021-03-08 23:54 UTC, merged

2021-03-08 23:54 UTC, ashie commented
Thanks!