Move node recommended setup to @fluent-org/logger
fluent/fluentd-docs-gitbook pull request #357
Opened 2021-08-25 16:10 UTC by jamiees2

Given https://github.com/fluent/fluent-logger-node/issues/177, [`fluent-logger-node`](https://github.com/fluent/fluent-logger-node) has been replaced with [`fluent-logger-forward-node`](https://github.com/fluent/fluent-logger-forward-node). This updates the documentation to reflect that.

2021-08-26 02:07 UTC, kenhys requested changes

2021-08-26 02:07 UTC, kenhys commented on language-bindings/nodejs.md
>  This article explains how to use it.
It looks good.

In addition, how about adding an explanation that fluent-logger-node is deprecated and recommend using fluent-logger-forward-node. It gives a hint for migration. 
something like:

`NOTE: ...`

2021-08-26 11:33 UTC, jamiees2 commented
urgh, I messed up the git fu to satisfy the DCO check.

2021-08-27 04:16 UTC, kenhys approved these changes
LGTM.

2021-08-27 04:17 UTC, merged

2021-08-27 04:17 UTC, kenhys commented
Thanks, @jamiees2