1.0: in_http: Add Authorization auth mechanism document
fluent/fluentd-docs-gitbook pull request #382
Opened 2021-12-14 08:17 UTC by cosmo0920

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

2021-12-14 09:40 UTC, kenhys commented on input/http.md
> +This authorization_token can handle not only Basic authentication but also other types of authentications.
```suggestion
This `authorization_token` can handle not only Basic authentication but also other types of authentications.
```

2021-12-14 12:15 UTC, cosmo0920 commented
Hmm, using GitHub suggestion commit breaks DCO. I'll fix it later.

2021-12-15 01:44 UTC, ashie commented on input/http.md
> +`authentication_token` will be interpreted as `<type>` and `<credentials>`:
```diff
- authentication_token
+ authorization_token
```

2021-12-15 01:50 UTC, ashie requested changes

2021-12-15 01:50 UTC, ashie commented on input/http.md
> +
Could you describe an example value like this?: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication

2021-12-15 04:30 UTC, ashie commented
[The patch](https://github.com/fluent/fluentd/pull/3572) is rejected.

2021-12-15 04:30 UTC, closed without merging